import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import {Roboto} from 'next/font/google';
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const font = Roboto({
  weight:['100','300','400','500','700','900'],
  subsets:['latin'],
})

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  title: "Symbios Labs",
  description: "Symbios Labs Website",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
